 all: main.cpp ./models/localSearch.cpp
	  g++ -o main main.cpp ./models/localSearch.cpp

# Test:
# 	python3 generateTestcases.py

# Output: 
# 	 python3 generateOutput.py


# test:
# #	python3 generateTestcases.py
# 	g++ -o main main.cpp ./models/SportsLayout.cpp
# #	g++ -o main main.cpp ./models/DFSbb.cpp
# #	g++ -o main main.cpp ./models/simulatedAnnealing.cpp
# 	python3 generateOutput.py
# #	python3 parsingLog.py
# # generateTest
# #  all: main.cpp SportsLayout.cpp
# # 	  g++ -o main main.cpp SportsLayout.cpp